### ISSUE TITLE
\dD's output not matching psql's

### ISSUE THREAD

**Issue by igncampa** [dbcli/pgspecial#75]
https://github.com/dbcli/pgspecial/blob/1ae9bab56f8c5e6e94eda577347cf5ffbf153bf5/pgspecial/dbcommands.py#L522-L536

This code was merged in #50 

This is a clever trick to save space when using `\dD`. Basically it concatenates 3 conditions into a single field.

```
psql

                        List of domains
 Schema | Name | Type | Collation | Nullable | Default | Check 
--------+------+------+-----------+----------+---------+-------
```
`Collation`, `Nullable` and `Default` concatenated into `Modifier`.  Each condition is turned into an empty string if nonexistant.

```
pgcli

+----------+--------+--------+------------+---------+
| Schema   | Name   | Type   | Modifier   | Check   |
|----------+--------+--------+------------+---------|
+----------+--------+--------+------------+---------+
```

I like it. My concern is that this might not be inherently clear to users actually wanting to check these conditions. Of course, if all of them are not null, it will be obvious.

Do you guys want to keep it or should we mimic `psql`'s output?

**Comment by j-bennet** [comment]
I actually prefer what `pgcli` does. There can be different opinions, of course. But we're not obligated to copy everything `psql` does, only what makes sense to us.

**Comment by igncampa** [comment]
Alright. Please feel free to close this issue. I don't do it myself just in case you might want to let a discussion build.
