### ISSUE TITLE
Cache files in package.

### ISSUE THREAD

**Issue by laixintao** [dbcli/pgspecial#94]
Hi @j-bennet I downloaded pgspecial-1.11.9.tar.gz from [pypi](https://pypi.org/project/pgspecial/1.11.9/) and found that there were some `__pycache__` and `.cache` in it, which I think it was added by accident.

```
tar xvf pgspecial-1.11.9.tar.gz
x pgspecial-1.11.9/
x pgspecial-1.11.9/PKG-INFO
x pgspecial-1.11.9/pgspecial/
x pgspecial-1.11.9/pgspecial/dbcommands.py
x pgspecial-1.11.9/pgspecial/namedqueries.py
x pgspecial-1.11.9/pgspecial/__init__.py
x pgspecial-1.11.9/pgspecial/iocommands.py
x pgspecial-1.11.9/pgspecial/main.py
x pgspecial-1.11.9/pgspecial/help/
x pgspecial-1.11.9/pgspecial/help/__init__.py
x pgspecial-1.11.9/pgspecial/help/commands.py
x pgspecial-1.11.9/tests/
x pgspecial-1.11.9/tests/conftest.py
x pgspecial-1.11.9/tests/pytest.ini
x pgspecial-1.11.9/tests/test_internal.py
x pgspecial-1.11.9/tests/__pycache__/
x pgspecial-1.11.9/tests/__pycache__/conftest.cpython-33-PYTEST.pyc
x pgspecial-1.11.9/tests/__pycache__/test_specials.cpython-33-PYTEST.pyc
x pgspecial-1.11.9/tests/__pycache__/conftest.cpython-27-PYTEST.pyc
x pgspecial-1.11.9/tests/__pycache__/test_specials.cpython-27-PYTEST.pyc
x pgspecial-1.11.9/tests/__pycache__/dbutils.cpython-33.pyc
x pgspecial-1.11.9/tests/dbutils.py
x pgspecial-1.11.9/tests/test_specials.py
x pgspecial-1.11.9/tests/dbutils.pyc
x pgspecial-1.11.9/tests/.cache/
x pgspecial-1.11.9/tests/.cache/v/
x pgspecial-1.11.9/tests/.cache/v/cache/
x pgspecial-1.11.9/tests/.cache/v/cache/lastfailed
```

I tried to fix release.py, however, when I re-packaging again with `python setup.py clean --all sdist`, the caches in `.tar.gz` are magically gone. Don't know why. Is the newer setuptools ignored the caches automatically maybe? I use `setuptools == 41.2.0`.

I open an issue here to remind you anyway :)

**Comment by j-bennet** [comment]
Thanks @laixintao, that's definitely something to keep in mind for the next release.

**Comment by j-bennet** [comment]
I think [this fixes it](https://github.com/dbcli/pgspecial/commit/62be9a04173843f699c9e64c6b264a818d402138). Unfortunately the last release still went out with cached files in it.

**Comment by laixintao** [comment]
That's strange XD

I built one locally and never see cache files for both git-commits before & after. Maybe we can delete .pyc files before build? :)
